# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2cdce899a3ae7602f8a8893361f78239a62d8f3c2d22682f7b42d54caf0ee733a48c673be4c076e1fc69165c1f92435b1e0e9398e0ba2346711a4eaabf402b1

test:
  secret_key_base: b9a95aea155e4f38db51cbc805c085b9ac71323409b9cf206bdf266f57b4227e637f8016fb04556df0bab4c9ee658aac69efdefae91a54f2d37ec062435d6a25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
